var svg=d3.select("#time_line")
			.append("svg")
			.attr("width","100%")
			.attr("height","100%");

var text_title=svg.append('text')
			.attr('x',"35%" )
			.attr('y',"9%" )
			.attr('fill',"black")
			.attr('font-size',"150%" )
			.attr('textLength',"30%" )
			.attr('text-align', "center")
			.attr('font-family',"黑体" )
		text_title.html("足球可视化系统")//title
var line1=svg.append('line')
		.attr('class',"timeline" )
		.attr('x1',"5%")
		.attr('y1',"15%")
		.attr('x2',"95%" )
		.attr('y2',"15%" )
var line2=svg.append('line')
		.attr('class',"timeline" )
		.attr('x1',"5%")
		.attr('y1',"24%")
		.attr('x2',"95%" )
		.attr('y2',"24%" )
var text1=svg.append('text')
		.attr("x","0.5%")
		.attr('y',"21%" )
		.attr('fill',"black" )
		.attr('font-size',"100%" )
		.attr('textLength', '3%');
	text1.html("时间轴");
	//two lines of time
function distribute(){
	for(var i=0;i<7;i++)
	{
		svg.append('line')
				.attr('class',"disline" )
				.attr('x1',(5+i*15).toString()+"%")
				.attr('y1',"15%")
				.attr('x2',(5+i*15).toString()+"%" )
				.attr('y2',"24%" );
			svg.append('text')
				.attr("x",(5+i*15).toString()+"%")
				.attr('y',"30%" )
				.attr('fill',"black")
				.attr('font-size',"100%")
				.attr('text-align',"center" )
				.html(i*15);		
			}
}
distribute();
var data1=[25,40,52,60,75,82,11,67,74,34]
var i=0
function court(){
	// for(var i=0;i<6;i++)
	// {
		var g=svg.selectAll("g")
				.data(data1)
				.enter().append('g')
				.attr("id",'g1')
				.on('mouseenter', function() {
					d3.select(this).select(".abc")
						.append('rect')
						.attr('id',"selected")
						.attr('x',"0%")
						.attr('y',"0%" )
						.attr('width',"100%")
						.attr('height',"100%")
						.style('fill', 'gray')
						.style('fill-opacity', '0.5')
					d3.select(this).select("#circletimeline")
						.attr("r","1.2%")
					/* Act on the event */
				})
				.on('mouseleave', function() {
					d3.select(this).select(".abc").select("#selected").remove()
					d3.select(this).select("#circletimeline")
						.attr("r","0.8%")
					/* Act on the event */
				})
		g.append("circle")
			.attr('id',"circletimeline" )
		    .attr('cx', function(d){
		    	return d.toString()+"%";
		    })
		    .attr('cy', "19.5%")
		    .attr('r', "0.8%")
		    .style('fill', function(d,i)
		    {
		    	if(i%2==0)
		    		return "red";
		    	else
		    		return "blue";
		    })//six circle
		var g1=g.append('svg')
				.attr('class', "abc")
				.attr('x',function(d,i){
					return (i*7).toString()+"%"
				})
				.attr('y',"35%" )
				.attr('width', "6%")
				.attr('height',"60%")
		var svg2=g1.append('g')
				.attr('id',"smallcourt" )
		svg2.append('rect')
			.attr('class',"fieldRect" )
			.attr('x',"0%")
			.attr('y',"0%" )
			.attr('width',"100%")
			.attr('height',"100%")
		svg2.append("circle")
			.attr('class',"fieldLines")
			.attr('cy',"11%" )
			.attr('cx',"50%" )
			.attr('r',"12.5%" )
		svg2.append('circle')
			.attr('class',"fieldLines" )
		    .attr('cx', "50%")
		    .attr('cy', "89%")
		    .attr('r', "12.5%")
		svg2.append('rect')
			.attr('class',"fieldLines" )
		    .attr('x',"20%" )
		    .attr('y', "0")
		    .attr('width', "60%")
		    .attr('height',"15%" )
		svg2.append('rect')
			.attr('class',"fieldLines" )
		    .attr('x',"20%" )
		    .attr('y', "85%")
		    .attr('width', "60%")
		    .attr('height',"15%" )
		svg2.append('rect')
			.attr('class',"fieldLines" )
		    .attr('x',"37%" )
		    .attr('y', "0")
		    .attr('width', "26%")
		    .attr('height',"5%" )
		svg2.append('rect')
			.attr('class',"fieldLines" )
		    .attr('x',"37%" )
		    .attr('y', "95%")
		    .attr('width', "26%")
		    .attr('height',"5%" )	
		svg2.append('line')
			.attr('class',"Gate" )
		    .attr('x1',"45%" )
		    .attr('y1', "0")
		    .attr('x2', "55%")
		    .attr('y2', "0%")
		svg2.append('line')
			.attr('class',"Gate" )
		    .attr('x1',"45%" )
		    .attr('y1', "100%")
		    .attr('x2', "55%")
		    .attr('y2', "100%")
		svg2.append("circle")
			.attr('class',"Points")
			.attr('cy',"11%" )
			.attr('cx',"50%" )
			.attr('r',"0.5%" )		
		svg2.append("circle")
			.attr('class',"Points")
			.attr('cy',"89%" )
			.attr('cx',"50%" )
			.attr('r',"0.5%" )
	 	svg2.append("circle")
			.attr('class',"fieldLines")
			.attr('cy',"50%" )
			.attr('cx',"50%" )
			.attr('r',"12.5%" )		
		svg2.append("circle")
			.attr('class',"Points")
			.attr('cy',"50%" )
			.attr('cx',"50%" )
			.attr('r',"0.5%" )	
		svg2.append('line')
			.attr('class',"fieldLines" )
		    .attr('x1',"0%" )
		    .attr('y1', "50%")
		    .attr('x2', "100%")
		    .attr('y2', "50%")
	 // }
}
court();